markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: Yikoo                                       			# 博客名称
    description: Let the past is past!--Goodbye.       			# 博客描述
    title: Yikoo --Let the past is past!               		# 网页标题
    url: http://yikoo.github.io/                     		    # 博客地址
    duoshuo:                                             		# 多说ID
    tongji:    525af40e10015630af834b6ae019ff2b                 # 百度统计ID
    qiniu:                                               		# 七牛云地址
author:		
    name:    Yikoo                                      		# 作者名称
    email: 295126165@qq.com                                     # 邮箱地址
    weibo: http://weibo.com/2935727977/profile?topnav=1&wvr=6	# 微博地址
    github:                                              		# GitHub地址
    logo: http://tp2.sinaimg.cn/2935727977/180/5716871564/1		# logo地址
    douban:
        name:                                            		# 豆瓣地址名称
        key:                                             		# 豆瓣API Key